compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: pnp

npmAuthToken: "${NODE_AUTH_TOKEN:-}"

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.1.0.cjs
