name: Master
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.1.4
          run_install: false
      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Build
        run: |
          pnpm -F=semantic-release-github-cjs build
          pnpm -F=postcss-colorguard build  
          pnpm -F=colorguard-processor build
          pnpm -F=colorguard-cli build
      - name: Publish package
        run: |
          pnpm -F=postcss-colorguard semantic-release
          pnpm -F=colorguard-processor semantic-release
          pnpm -F=colorguard-cli semantic-release
        env:
          NPM_TOKEN: ${{ secrets.YARN_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
