name: Publish
on:
  release:
    types:
      - created
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - name: Install dependencies
        run: pnpm install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Build
        run: |
          pnpm -F=postcss-colorguard build  
          pnpm -F=colorguard-processor build
          pnpm -F=colorguard-cli build
      - name: Prepare release config
        run: |
          git config --global user.name 'Bryan Thomas'
          git config --global user.email '49354825+bryanjtc@users.noreply.github.com'
      - name: Publish release
        run: pnpm nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
