name: Test release

on:
  pull_request:
      branches:
          - master

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with :
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v4         
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Set yarn config
        run: yarn config set npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - name: Build
        run: |
          yarn workspace postcss-colorguard build  
          yarn workspace colorguard-processor build
          yarn workspace colorguard-cli build
      - name: Semantic Release dry run
        id: dry-release
        run: unset GITHUB_ACTIONS && yarn workspaces foreach -W --no-private --topological-dev run semantic-release --dry-run --no-ci --branches ${HEAD_REF} -e semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
